name: Update Decode Output

on:
  schedule:
    - cron: '5 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the main branch (instead of key-gen)
      - uses: actions/checkout@v3
        with:
          ref: main  # Changed from 'key-gen' to 'main'
      
      # Generate JSON file
      - name: Generate JSON
        working-directory: scripts/decoder
        run: |
          npm install
          npm start
      
      # Commit and push changes to main branch
      - name: Commit generated JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add scripts/decoder/generated/kai.json
          git commit -m "Update generated kai.json"
          git push origin main  # Push to main branch
